### ISSUE TITLE
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by lracicot** [symphoniacloud/code-pipeline-slack-notifier#11]

**Comment by mikebroberts** [comment]
Thanks! I was hoping that AWS Chatbot (https://aws.amazon.com/chatbot/) would replace this but it seems to have got stuck in beta.

**Comment by david2331** [comment]
Tested the chatbot service from AWS, surprisingly it's so easy to configure and it work just like that. 

Thanks

**Comment by mikebroberts** [comment]
Yep, I've switched to using Chatbot now - it does everything I need. I'll likely publish a new SAR to help with using it, but it will be entirely separate from this app. As such I consider this app deprecated. 

FWIW the below helps get started with Chatbot, but there's still some manual configuration needed in the Chatbot console too. (Assumes a resource / parameter named `CodePipeline`)

```
  PipelineNotificationsTopic:
    Type: AWS::SNS::Topic
  
  PipelineNotificationsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref PipelineNotificationsTopic
      PolicyDocument: 
        Statement:
        - Action: 'SNS:Publish'
          Effect: Allow
          Resource: !Ref PipelineNotificationsTopic
          Principal:
            Service: codestar-notifications.amazonaws.com
  
  NotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      # Name is required, unlike for most resource types, so we include the stack name to avoid name clashes
      Name: !Sub '${CodePipeline}-${AWS::StackName}'
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
      DetailType: FULL
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-failed
        - codepipeline-pipeline-pipeline-execution-canceled
        - codepipeline-pipeline-pipeline-execution-started
        - codepipeline-pipeline-pipeline-execution-resumed
        - codepipeline-pipeline-pipeline-execution-succeeded
        - codepipeline-pipeline-pipeline-execution-superseded
      Targets:
        - TargetType: SNS
          TargetAddress: !Ref PipelineNotificationsTopic
```
